sudo: required

language: python

env: master

python:
  - '3.6'

services:
  - docker

env:
  global:
  - secure: azT7pYuL3rsKVCfi6U/xt8K2NmCtdtg7NW3UnQTv9lxZeLtBjpqk5iE19FwovD9s0rkcL6vwJ8DWMjjK3XyB7Ls+JACgwdRk4A06NSBuU4W+Mk0o4FtmCURH0vnsNnHX//OqEGBktnFhQVpYYd544opWqeMq3PvccmaNJ1a2j0WMBIuBYeSvxjL7b/wZMAqMxG+VES7/URRJyUwH6WHz8wiTDOCwyG75FJCVes9lDz4W8mW5jW6DXuyrZNEabTpArkeCd8iN9V0aYtpXuG4Zn2cmBfDaH2wBVB2w4xF6NZcx0yHXPkB3xMh0BIIY0dO9ZQk6XJSxumYdnI0YTn/FPsLUkqEjByw9roIp38u7Qrr9yFxRltQ5bWOsyGyWqMBaAF9sdT7AB0LK2HTFjxWF6B2PtFdKGk1b2EEIYVgtvqKR6VcBJbrMLnKfevmAkYAlvonnw7zFF1+CgehD/vcenQ1WNdq7rTQEknoCMOuRwfQY8GVKx9ZVbC9hnmEij1gSkdZ3toCHmorQohHY3uyu5ETr+Jy8oAql8phvovEam6K1y3lnGhzgLbTtwMfbP+hbViJXJqer6wiE+QOQ8vuIrTTFNuROrf6V3eYdT8U9+GeVAAAUCxQR/gcAo/iONLyS8vp7dhE1ym0k/n/gqpciX+SXZA7QFaL64Z+awsMs2gQ=
  - secure: AXt/dNNV1ZuycHzfkjrOuf/TaStKPqptih616LcJiX8RE6gO5aSENah9wG+HIo0FQxPCcdmaQJOoqRn0cCoNUHu8zxmhym24jA2ZWQtC4xmOZ2FVMDFIgH3cZTqBuzqWW9eHjxqA0JS7eDUHNaWDFIEDBCFS8y3PKZILv4KQYJcfzeNB3LoZQWYqWTWrFjtFB7Rc1VAPtnHjamKjIUi+lr3mICMYjLUAr09Rr0LQRrccMTFYKhZPh5DonLAzQyQNJ+tSgTjSORFB0nBHyn1DhVEUbFBqZioIRGu2KrBQG6JuXwKgI5kZFGjcTh0fYyb6RZPNHzkE36c/Xxah2FOmONyT3iZNh4b+ydfZhMw5ELsuxiOZ8Pc86iM9mEk8bUwDhe7q1f/EFj4K7KFp7SZmeRGKAY2V7oWwIpELpZ4pjG0AnCJbtatpI8Jo/BSRIrfLfiMiv6HZwwlJnU0jxEnNyn6urrx6YSJWuu3biw2XSnZ4Jlbw88eV6f7ervSXwn6dxrxwTC0D8mrWog8Yl8YeAfuT7QCBvJAVbItTQqNFKIYo71C06c7VJnhXrIpBq/mKjb1n2QzV8VbIMtIFbpNjp4N4tgP/6JeGEsMkk5/ozHym4qQO2StTEW8A4FMjA/cA9MUFo+RD1Eu2SukC23KhRqC9KJar3AW4Ntge1Ma/FF8=

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  - inv test

deploy:
  provider: script
  script: inv docker-build docker-push
